### ISSUE TITLE
Could not get latest yarn build for version

### ISSUE THREAD

**Issue by Madis0** [natanfudge/Not-Enough-Crashes#1]
Not sure what can it affect, but I saw it in the log so I thought it was worth mentioning.
```
[20:33:08] [main/ERROR]: Could not get latest yarn build for version
java.nio.file.NoSuchFileException: /home/madis/.minecraft/not-enough-crashes/yarn-version.txt
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_232]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_232]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_232]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_232]
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434) ~[?:1.8.0_232]
	at java.nio.file.Files.newOutputStream(Files.java:216) ~[?:1.8.0_232]
	at java.nio.file.Files.write(Files.java:3292) ~[?:1.8.0_232]
	at fudge.notenoughcrashes.stacktrace.YarnVersion.getLatestBuildForCurrentVersion(YarnVersion.java:40) ~[notenoughcrashes-1.0.9+1.15.jar:?]
	at fudge.notenoughcrashes.stacktrace.StacktraceDeobfuscator.downloadAndCacheMappings(StacktraceDeobfuscator.java:47) ~[notenoughcrashes-1.0.9+1.15.jar:?]
	at fudge.notenoughcrashes.stacktrace.StacktraceDeobfuscator.init(StacktraceDeobfuscator.java:83) ~[notenoughcrashes-1.0.9+1.15.jar:?]
	at fudge.notenoughcrashes.NotEnoughCrashes.initStacktraceDeobfuscator(NotEnoughCrashes.java:54) ~[notenoughcrashes-1.0.9+1.15.jar:?]
	at fudge.notenoughcrashes.NotEnoughCrashes.onInitialize(NotEnoughCrashes.java:35) ~[notenoughcrashes-1.0.9+1.15.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32) [fabric-loader-0.7.2+build.174.jar:?]
	at net.minecraft.class_310.redirect$zee000$redirectModEntryPoints(class_310.java:4524) [intermediary-fabric-loader-0.7.2+build.174-1.15.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:391) [intermediary-fabric-loader-0.7.2+build.174-1.15.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:164) [intermediary-fabric-loader-0.7.2+build.174-1.15.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138) [fabric-loader-0.7.2+build.174.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.2+build.174.jar:?]
```

Minecraft 1.15 / Fabric API 0.4.23 b 276 / NEC 1.0.9

**Comment by natanfudge** [comment]
Can you verify this is fixed in the latest version?

**Comment by Madis0** [comment]
Yes, can no longer reproduce.
