### ISSUE TITLE
Fabric 1.17.1 crash

### ISSUE THREAD

**Issue by ElFamosoCrockette** [natanfudge/Not-Enough-Crashes#103]
The game crashed whilst tesselating liquid in world
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.get(net.minecraft.class_3611)" because "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.INSTANCE" is null
Code de sortie : -1

My games crash when i go on a server and i dont know why
mod : Autofish-0.9.3-fabric-mc1.17
          fabric-api-0.42.0+1.17
          optifabric-1.12.6
          OptiFine_1.17.1_HD_U_H1

**Comment by ElFamosoCrockette** [comment]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 03/12/2021 18:19
Description: Tesselating liquid in world

java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.get(net.minecraft.class_3611)" because "net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandlerRegistry.INSTANCE" is null
	at me.modmuss50.optifabric.compat.fabricrenderingfluids.FluidRendererFixExternal.needsOptiFine(FluidRendererFixExternal.java:19)
	at me.modmuss50.optifabric.compat.fabricrenderingfluids.FluidRendererFixExternal.needsOptiFine(FluidRendererFixExternal.java:14)
	at net.minecraft.class_775.method_3347(class_775.java:140)
	at net.fabricmc.fabric.impl.client.rendering.fluid.FluidRenderHandlerRegistryImpl.renderFluid(FluidRenderHandlerRegistryImpl.java:124)
	at net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler.renderFluid(FluidRenderHandler.java:85)
	at net.minecraft.class_775.tessellateViaHandler(class_775.java:593)
	at net.minecraft.class_775.handler$zdk000$tesselate(class_775.java:568)
	at net.minecraft.class_775.method_3347(class_775.java)
	at net.minecraft.class_776.method_3352(class_776.java:103)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:975)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:850)
	at net.minecraft.class_846.method_22757(class_846.java:194)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1806)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.modmuss50.optifabric.compat.fabricrenderingfluids.FluidRendererFixExternal.needsOptiFine(FluidRendererFixExternal.java:19)
	at me.modmuss50.optifabric.compat.fabricrenderingfluids.FluidRendererFixExternal.needsOptiFine(FluidRendererFixExternal.java:14)
	at net.minecraft.class_775.method_3347(class_775.java:140)
	at net.fabricmc.fabric.impl.client.rendering.fluid.FluidRenderHandlerRegistryImpl.renderFluid(FluidRenderHandlerRegistryImpl.java:124)
	at net.fabricmc.fabric.api.client.render.fluid.v1.FluidRenderHandler.renderFluid(FluidRenderHandler.java:85)
	at net.minecraft.class_775.tessellateViaHandler(class_775.java:593)
	at net.minecraft.class_775.handler$zdk000$tesselate(class_775.java:568)
	at net.minecraft.class_775.method_3347(class_775.java)

-- Block being tesselated --
Details:
	Block location: World: (11,67,-28), Section: (at 11,3,4 in 0,4,-2; chunk contains blocks 0,0,-32 to 15,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)

-- Affected level --
Details:
	All players: 1 total; [class_746['Crockette'/8883, l='ClientLevel', x=0.50, y=65.10, z=0.50]]
	Chunk stats: 18225, 81
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,65,0), Section: (at 0,1,0 in 0,4,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 5062 game time, 3505885 day time
	Server brand: §b§lSkySword§r
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:469)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_846.method_22755(class_846.java:200)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1806)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Alacrity.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 831370056 bytes (792 MiB) / 1845493760 bytes (1760 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600G with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3,69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512,00
	Graphics card #0 deviceId: 0x1636
	Graphics card #0 versionInfo: DriverVersion=27.20.22012.1
	Graphics card #1 name: NVIDIA GeForce GTX 1650
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095,00
	Graphics card #1 deviceId: 0x1f82
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7208
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 3,20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 24452,25
	Virtual memory used (MB): 14895,06
	Swap memory total (MB): 8704,00
	Swap memory used (MB): 82,32
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autofish: Autofish 0.9.3
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.34
		fabric: Fabric API 0.42.0+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.1+5847535018
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+5847535018
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.10+5847535018
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.4+5847535018
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.5+5847535018
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.0+5847535018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.6+5847535018
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.0+5847535018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.0+5847535018
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+5847535018
		fabricloader: Fabric Loader 0.11.7
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		optifabric: OptiFabric 1.12.6
	Launched Version: fabric-loader-0.11.7-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ERR
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Alacrity.zip
	Current Language: Français (France)
	CPU: 12x AMD Ryzen 5 4600G with Radeon Graphics
	OptiFine Version: OptiFine_1.17.1_HD_U_H1
	OptiFine Build: 20211104-012451
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: DrDestens+MinecraftShaders+v1.3.2.zip
	OpenGlVersion: 3.2.0 NVIDIA 472.08
	OpenGlRenderer: NVIDIA GeForce GTX 1650/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.17.1
	OptiFine jar version: OptiFine_1.17.1_HD_U_H1
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/allan/AppData/Roaming/.minecraft/.optifine/OptiFine_1.17.1_HD_U_H1/Optifine-mapped.jar
	OptiFabric error: <None>

**Comment by natanfudge** [comment]
Completely unrelated to this mod.
