### ISSUE TITLE
Game doesn't close properly

### ISSUE THREAD

**Issue by ElBread3** [natanfudge/Not-Enough-Crashes#109]
Game version: 1.18.1 Fabric
Mod version 4.1.3

Minecraft's JDK does not close, and stays in background, after quit button or window close button pressed
The output log prints this:

Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: fudge.notenoughcrashes.utils.SystemExitBlockedException: An attempt was made to forcefully close the game with no stack trace (see stack trace). Not Enough Crashes made the game simply crash instead since the forceCrashScreen option is enabled.
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.4)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:604)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: fudge.notenoughcrashes.utils.SystemExitBlockedException: An attempt was made to forcefully close the game with no stack trace (see stack trace). Not Enough Crashes made the game simply crash instead since the forceCrashScreen option is enabled.
	at fudge.notenoughcrashes.utils.SystemExitBlock$1.checkPermission(SystemExitBlock.java:12)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:629)
	at java.lang.Runtime.exit(Runtime.java:113)
	at java.lang.System.exit(System.java:1860)
	at net.minecraft.client.MinecraftClient.stop(MinecraftClient:1026)
	at net.minecraft.client.main.Main.main(Main:254)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:602)
	... 2 more
Uncaught exception in thread "Render thread"
fudge.notenoughcrashes.utils.SystemExitBlockedException: An attempt was made to forcefully close the game with no stack trace (see stack trace). Not Enough Crashes made the game simply crash instead since the forceCrashScreen option is enabled.
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.4)
	at fudge.notenoughcrashes.utils.SystemExitBlock$1.checkPermission(SystemExitBlock.java:12)
	at java.lang.SecurityManager.checkExit(SecurityManager.java:629)
	at java.lang.Runtime.exit(Runtime.java:113)
	at java.lang.System.exit(System.java:1860)
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:136)
	at net.fabricmc.loader.impl.gui.FabricGuiEntry.displayError(FabricGuiEntry.java:102)
	at net.fabricmc.loader.impl.launch.FabricLauncherBase.handleFormattedException(FabricLauncherBase.java:81)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:79)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Really annoying because it won't launch when already open, so I have to use Task Manager..

**Comment by natanfudge** [comment]
Hey, please disable 'forceCrashScreen' to work around this issue temporarily.
