### ISSUE TITLE
fabric-0.12.12-1.18.1 crash on launch

### ISSUE THREAD

**Issue by cwillsey06** [natanfudge/Not-Enough-Crashes#119]
Partial clone of #52, but the issue is different enough to warrant a new issue.
```
[06:21:34] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[06:21:35] [main/WARN]: Warnings were found!
 - Mod 'MultiConnect' (multiconnect) 1.5.10 conflicts with any version of mod 'Immersive Portals' (immersive_portals), which is present with the following versions: 1.2.3!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'MultiConnect' (multiconnect) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
	 - Mod 'Immersive Portals' (immersive_portals) 1.2.3 is being loaded from /Users/coltranewillsey/Library/Application Support/minecraft/mods/immersive-portals-1.2.3-mc1.18.1-fabric.jar
[06:21:35] [main/INFO]: Loading 80 mods:
	- betterthirdperson 1.6.0
	- cloth-api 3.1.61
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-client-events-v0 3.1.61 via cloth-api
	- cloth-common-events-v1 3.1.61 via cloth-api
	- cloth-config 6.1.48
	- cloth-datagen-api-v1 3.1.61 via cloth-api
	- cloth-scissors-api-v1 3.1.61 via cloth-api
	- cloth-utils-v1 3.1.61 via cloth-api
	- effective 1.1
	- fabric 0.46.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
	- fabric-renderer-api-v1 0.4.10+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.13+b0b66fc365 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-conditions-api-v1 1.0.1+13eda06565 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.1.0+0a73a6c265 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fallingleaves 1.9.0+1.18.1
	- illuminations 1.10.2
	- imm_ptl_core 1.2.3 via immersive_portals
	- immersive_portals 1.2.3
	- java 17
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- kirin 1.10.0-beta.2 via presencefootsteps
	- lambdynlights 2.1.0+1.17
	- logical_zoom 0.0.13
	- minecraft 1.18.1
	- modmenu 3.0.1
	- multiconnect 1.5.10
	- multiconnect-api 1.5.10 via multiconnect
	- notenoughcrashes 4.1.4+1.16.5
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_joml_joml 1.10.2 via sodium
	- pehkui 3.1.0+1.14.4-1.18.1
	- presencefootsteps 1.4.0
	- pride 1.1.0+1.17 via lambdynlights
	- q_misc_util 1.2.3 via immersive_portals
	- sodium 0.4.0-alpha6+build.14
	- sound_physics_remastered 1.18.1-1.0.4
	- spruceui 3.3.0+1.17 via lambdynlights
[06:21:35] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/Users/coltranewillsey/Library/Application%20Support/minecraft/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[06:21:35] [main/INFO]: Compatibility level set to JAVA_16
[06:21:35] [main/INFO]: Compatibility level set to JAVA_17
[06:21:36] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[06:21:36] [main/INFO]: Sodium found. Applying compatibility mixin...
[06:21:37] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'com.mojang.bridge.game.GameVersion net.minecraft.class_3797.method_16672()'
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.NoSuchMethodError: 'com.mojang.bridge.game.GameVersion net.minecraft.class_3797.method_16672()'
	at fudge.notenoughcrashes.fabric.StacktraceDeobfuscator.<clinit>(StacktraceDeobfuscator.java:29) ~[notenoughcrashes-4.1.4+1.16.5-fabric.jar:?]
	at net.minecraft.client.main.Main.handler$bio000$asSoonAsPossible(Main.java:517) ~[fabric-loader-0.12.12-1.18.1.jar:?]
	at net.minecraft.client.main.Main.main(Main.java) ~[fabric-loader-0.12.12-1.18.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 2 more
```
By the way, you said to use version 3.4.1, which I obviously cannot use due to it being 1.17x, and to enable `forceCrashScreen` in config, but since the mod is never initialized, no such file exists. (or I can't find it)

**Comment by natanfudge** [comment]
Hey, you're using the 1.16.5 variant of 4.1.4. Please try again with the correct 1.17 variant that matches your Minecraft version.

**Comment by cwillsey06** [comment]
Aw... yeah that worked. That's what happens when you don't sleep and debug like a pirate. Thanks... lol
