### ISSUE TITLE
Gaming Is Still Running And I Can Move By Arrow keys, But Crash frame Appears With Compulsion

### ISSUE THREAD

**Issue by jsfnqcw** [natanfudge/Not-Enough-Crashes#132]
After I delete this mod,I can play it again  :(  
This is the crash report:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022/4/30 下午8:31
Description: Batching chunks

java.lang.IllegalStateException: not enough data
	at net.minecraftforge.client.model.pipeline.BakedQuadBuilder.build(BakedQuadBuilder.java:124) ~[forge:?] {re:classloading}
	at mods.betterfoliage.model.HalfBakedKt.bake(HalfBaked.kt:108) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.model.TuftMeshesKt.buildTufts(TuftMeshes.kt:105) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.model.TuftMeshesKt.buildTufts$default(TuftMeshes.kt:104) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardCactusModel$Companion$cactusArmModels$2.invoke(Cactus.kt:85) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardCactusModel$Companion$cactusArmModels$2.invoke(Cactus.kt:75) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.util.LazyInvalidatable.getValue(Caching.kt:33) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardCactusModel$Companion.getCactusArmModels(Cactus.kt) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardCactusModel.prepare(Cactus.kt:58) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.model.WeightedModelWrapper.prepare(SpecialRenderModels.kt:43) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.model.WeightedModelWrapper.prepare(SpecialRenderModels.kt:31) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.pipeline.RenderCtxBase$Companion.reset(RenderCtxBase.kt:76) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.pipeline.RenderCtxBase.reset(RenderCtxBase.kt) ~[betterfoliage:2.7.1] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.handler$cof000$onStartBlockRender(ChunkRenderDispatcher.java:1097) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.optifine.mixins.json:MixinOptifineChunkRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:802) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.optifine.mixins.json:MixinOptifineChunkRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:735) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:APP:betterfoliage.optifine.mixins.json:MixinOptifineChunkRendererDispatcher,pl:mixin:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:192) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.BakedQuadBuilder.build(BakedQuadBuilder.java:124) ~[forge:?] {re:classloading}
	at mods.betterfoliage.model.HalfBakedKt.bake(HalfBaked.kt:108) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.model.TuftMeshesKt.buildTufts(TuftMeshes.kt:105) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.model.TuftMeshesKt.buildTufts$default(TuftMeshes.kt:104) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardCactusModel$Companion$cactusArmModels$2.invoke(Cactus.kt:85) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardCactusModel$Companion$cactusArmModels$2.invoke(Cactus.kt:75) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.util.LazyInvalidatable.getValue(Caching.kt:33) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardCactusModel$Companion.getCactusArmModels(Cactus.kt) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.block.vanilla.StandardCactusModel.prepare(Cactus.kt:58) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.model.WeightedModelWrapper.prepare(SpecialRenderModels.kt:43) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.model.WeightedModelWrapper.prepare(SpecialRenderModels.kt:31) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.pipeline.RenderCtxBase$Companion.reset(RenderCtxBase.kt:76) ~[betterfoliage:2.7.1] {re:classloading}
	at mods.betterfoliage.render.pipeline.RenderCtxBase.reset(RenderCtxBase.kt) ~[betterfoliage:2.7.1] {re:mixin,re:classloading}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['_NMSL_'/2535, l='ClientLevel', x=1622.10, y=64.00, z=-5935.51]]
	Chunk stats: Client Chunk Cache: 5041, 701
	Level dimension: minecraft:overworld
	Level spawn location: World: (1437,80,-6502), Chunk: (at 13,5,10 in 89,-407; contains blocks 1424,0,-6512 to 1439,255,-6497), Region: (2,-13; contains chunks 64,-416 to 95,-385, blocks 1024,0,-6656 to 1535,255,-6145)
	Level time: 5055648 game time, 2108974 day time
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:xaerominimap:xaero_clientworldclass,xf:fml:xaeroworldmap:xaero_wm_clientworldclass,pl:mixin:APP:betterweather.mixins.json:client.MixinClientWorld,pl:mixin:APP:waterdripsound.mixins.json:client.MixinClientWorld,pl:mixin:APP:starlight.mixins.json:client.world.ClientWorldMixin,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:blue_skies.mixins.json:ClientWorldMixin,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:endergetic.mixins.json:ClientWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:client.MixinClientWorld,pl:mixin:APP:betterfoliage.common.mixins.json:MixinClientWorld,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customskinloader:MinecraftTransformer,pl:mixin:APP:randompatches.mixins.json:client.MinecraftMixin,pl:mixin:APP:chat_heads.mixins.json:MinecraftMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftMixin,pl:mixin:APP:charm.mixins.json:accessor.MinecraftAccessor,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:APP:quitconfirm.mixins.json:MixinMinecraft,pl:mixin:APP:IngameIME-forge.mixins.json:MixinMinecraft,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:APP:mixins.dynmus.json:MinecraftMixin,pl:mixin:APP:mixins.betterthirdperson.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:outer_end.mixins.json:BackgroundMusicMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:drippyloadingscreen.mixin.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:198) ~[?:?] {re:mixin,xf:OptiFine:default,re:classloading,xf:OptiFine:default,pl:mixin:A}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1742) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11.0.12, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5662004040 bytes (5399 MB) / 10724048896 bytes (10227 MB) up to 10724048896 bytes (10227 MB)
	CPUs: 8
	JVM Flags: 26 total; -Xms10G -Xmx10G -Xss4M -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSConcurrentMTEnabled -XX:ParallelGCThreads=8 -XX:+UnlockExperimentalVMOptions -XX:+ExplicitGCInvokesConcurrent -XX:MaxGCPauseMillis=50 -XX:+AlwaysPreTouch -XX:+UseStringDeduplication -XX:-OmitStackTraceInFastThrow -XX:+OptimizeStringConcat -XX:+UseAdaptiveGCBoundary -XX:NewRatio=3 -XX:+UseFastAccessorMethods -XX:CMSInitiatingOccupancyFraction=75 -XX:+CMSScavengeBeforeRemark -XX:+UseCMSInitiatingOccupancyOnly -XX:-UseAdaptiveSizePolicy -XX:-DontCompileHugeMethods -Xmn128m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+IgnoreUnrecognizedVMOptions
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.29.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.29.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.29
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.17.0

**Comment by natanfudge** [comment]
I can't know what is going on if you don't provide a way for me to reproduce this.
