### ISSUE TITLE
Incompatible with autoreconnect

### ISSUE THREAD

**Issue by natanfudge** [natanfudge/Not-Enough-Crashes#139]
[21:46:47] [Render thread/INFO]: Disconnect from <ip>
[21:46:47] [Render thread/INFO]: UDP closed
[21:46:47] [Input Device Recorder/INFO]: Recorder cleanup
[21:46:47] [Input Device Recorder/INFO]: Close opus encoder
[21:46:47] [Render thread/INFO]: Minimap session finalized.
[21:46:47] [Render thread/INFO]: Finalizing world map session...
[21:46:48] [Thread-18/INFO]: World map force-cleaned!
[21:46:48] [Render thread/INFO]: World map session finalized.
[21:46:48] [Render thread/INFO]: Stopping JEI
[21:46:48] [Render thread/INFO]: Stopping worker threads
[21:46:48] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[21:46:48] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "autoreconnect.reconnect.ReconnectStrategy.nextAttempt()" because "this.reconnectStrategy" is null
    at autoreconnect.AutoReconnect.startCountdown(AutoReconnect.java:68) ~[autoreconnect-2.1.0-beta.jar:?]
    at net.minecraft.class_419.handler$zdo001$constructor(class_419.java:1037) ~[client-intermediary.jar:?]
    at net.minecraft.class_419.<init>(class_419.java:18) ~[client-intermediary.jar:?]
    at net.minecraft.class_634.method_10839(class_634.java:758) ~[client-intermediary.jar:?]
    at net.minecraft.class_2535.method_10768(class_2535.java:421) ~[client-intermediary.jar:?]
    at net.minecraft.class_636.method_2927(class_636.java:296) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1574(class_310.java:1761) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1523(class_310.java:1101) ~[client-intermediary.jar:?]
    at net.minecraft.class_310.method_1514(class_310.java:734) [client-intermediary.jar:?]
    at net.minecraft.client.main.Main.main(Main.java:237) [client-intermediary.jar:?]
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
[21:46:49] [CraftPresence-ShutDown-Handler/INFO]: Shutting down CraftPresence...

But only if i use not enough crashes in combinations, maybe a conflict? :o
But if this mod crashes, the conflict must be on the autoreconnector side, right?

**Comment by natanfudge** [comment]
Not sure how to reproduce crash, waiting for response
