### ISSUE TITLE
Crash probably because not enough crashes crashed(?)

### ISSUE THREAD

**Issue by 5ur3z** [natanfudge/Not-Enough-Crashes#157]
**Describe the bug**
Crash probably because not enough crashes crashed(?)

**To Reproduce**
1.join a server
2.play for sometime
3.crashed with memory leak

**Crash Log:**
[游戏崩溃前的输出.txt](https://github.com/natanfudge/Not-Enough-Crashes/files/10087733/default.txt)

[00:55:15] [Render thread/ERROR]: Out of memory
java.lang.OutOfMemoryError: null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]
	at org.lwjgl.system.MemoryUtil.nmemReallocChecked(MemoryUtil.java:484) ~[lwjgl-3.2.2.jar:?]
	at org.lwjgl.system.MemoryUtil.memRealloc(MemoryUtil.java:517) ~[lwjgl-3.2.2.jar:?]
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferBuilder.setBufferSize(VertexBufferBuilder.java:36) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.model.vertex.buffer.VertexBufferBuilder.start(VertexBufferBuilder.java:88) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuildBuffers.init(ChunkBuildBuffers.java:62) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:55) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:273) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.stealTask(ChunkBuilder.java:233) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.findNext(WorkStealingFutureDrain.java:54) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.common.util.collections.WorkStealingFutureDrain.hasNext(WorkStealingFutureDrain.java:28) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:123) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:59) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:334) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:312) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:197) ~[sodium-fabric-mc1.18.2-0.4.1_(replaymod_compatible).jar:?]
	at net.minecraft.client.render.WorldRenderer.setupTerrain(WorldRenderer:18485) ~[?:?]
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1235) ~[?:?]
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1034) ~[?:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:813) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) [JavaWrapper.jar:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) [JavaWrapper.jar:?]
[00:55:45] [Render thread/INFO]: Saved 'betterstats' config.

**Game Instance:**
Link to the curseforge/multimc game instance, or to a zip containing your game instance. For most issues, you must provide _something_ including the mods, saves, and configs you have used.

**Comment by JaaiDead** [comment]
maybe sodium is the cause? 
Or Try deleting the crashes mod

**Comment by 5ur3z** [comment]
> maybe sodium is the cause? 
> 
> Or Try deleting the crashes mod

then the sodium author told me to delete this mod, then it stop crashes..

**Comment by cootshk** [comment]
You're out of memory
Increase the memoryu given to minecraft
(4G or 4196 MB is enough)

**Comment by JaaiDead** [comment]
Sodium?
