### ISSUE TITLE
mixin filename trips up NEC

### ISSUE THREAD

**Issue by natanfudge** [natanfudge/Not-Enough-Crashes#171]
Suspected Mods: java.nio.file.InvalidPathException: Illegal char <:> at index 11: #continuity:continuity.mixins.json
    at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
    at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
    at java.base/java.nio.file.Path.resolve(Path.java:515)
    at net.fabricmc.loader.api.ModContainer.findPath(ModContainer.java:68)
    at fudge.notenoughcrashes.fabric.platform.FabricPlatform.lambda$modContainsFile$2(FabricPlatform.java:92)
    at java.base/java.util.Optional.flatMap(Optional.java:289)
    at fudge.notenoughcrashes.fabric.platform.FabricPlatform.modContainsFile(FabricPlatform.java:92)
    at fudge.notenoughcrashes.stacktrace.ModIdentifier.lambda$identifyFromMixin$8(ModIdentifier.java:155)
    at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
    at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromMixin(ModIdentifier.java:151)
    at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromThrowable(ModIdentifier.java:76)
    at fudge.notenoughcrashes.stacktrace.ModIdentifier.lambda$identifyFromStacktrace$2(ModIdentifier.java:42)
    at fudge.notenoughcrashes.stacktrace.ModIdentifier.visitChildrenThrowables(ModIdentifier.java:52)
    at fudge.notenoughcrashes.stacktrace.ModIdentifier.identifyFromStacktrace(ModIdentifier.java:41)
    at fudge.notenoughcrashes.stacktrace.ModIdentifier.lambda$getSuspectedModsOf$0(ModIdentifier.java:34)
    at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
    at fudge.notenoughcrashes.stacktrace.ModIdentifier.getSuspectedModsOf(ModIdentifier.java:34)
    at net.minecraft.class_128.mdac3a6b$notenoughcrashes$lambda$beforeSystemDetailsAreWritten$1$0(class_128.java:535)
    at net.minecraft.class_6396.method_37123(class_6396.java:66)
    at net.minecraft.class_128.handler$bon000$notenoughcrashes$beforeSystemDetailsAreWritten(class_128.java:533)
    at net.minecraft.class_128.method_555(class_128.java:79)
    at net.minecraft.class_128.method_568(class_128.java:134)
    at net.minecraft.class_128.method_569(class_128.java:154)
    at fudge.notenoughcrashes.stacktrace.CrashUtils.outputReport(CrashUtils.java:43)
    at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.displayCrashScreen(InGameCatcher.java:101)
    at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:35)
    at net.minecraft.class_310.modify$bpb000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:10063)
    at net.minecraft.class_310.method_1514(class_310.java:824)
    at net.minecraft.client.main.Main.main(Main.java:250)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:524)
    at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
    at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
See https://hastebin.skyra.pw/hekufomevu.htm

**Comment by natanfudge** [comment]
Should be fixed in 4.4.5
