### ISSUE TITLE
NOT ENOUGH CRASHES CRASHING ON FABRIC 1.17.1

### ISSUE THREAD

**Issue by Lokemol** [natanfudge/Not-Enough-Crashes#189]
So everytime i try to open MC with NEC in the mods folder it crashes, this is the crash report:

MultiMC version: 0.7.0-3863

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:bdf::57, 13.107.246.57]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::57, 13.107.246.57]

api.mojang.com resolves to:
    [2620:1ec:bdf::57, 13.107.246.57]

Minecraft folder is:
Z:/Minecraft/MULTIMC/MultiMC/instances/1.17.1/.minecraft

Java path is:
C:/Program Files/Java/jdk-16.0.2/bin/javaw.exe

Checking Java version...
Java is version 16.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  Z:/Minecraft/MULTIMC/MultiMC/instances/1.17.1/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/github/oshi/oshi-core/5.7.5/oshi-core-5.7.5.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.16.0/log4j-slf4j18-impl-2.16.0.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.16.0/log4j-api-2.16.0.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.16.0/log4j-core-2.16.0.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/net/fabricmc/intermediary/1.17.1/intermediary-1.17.1.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/net/fabricmc/fabric-loader/0.15.7/fabric-loader-0.15.7.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/mojang/minecraft/1.17.1/minecraft-1.17.1-client.jar

Native libraries:
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  Z:/Minecraft/MULTIMC/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] architectury-2.10.12.jar
  [✔️] architectury-2.10.5.jar
  [✔️] autoconfig1u-3.3.1.jar
  [✔️] bedrock-miner-1.0.0-for-Minecraft-1.17.1.jar
  [✔️] betterthanmending-1.3.0.jar
  [✔️] carpet-extra-1.17.1-1.4.57.jar
  [✔️] carpet-fixes-1.17.1-1.3.0+v211201.jar
  [✔️] carpet-tis-addition-mc1.17.1-v1.59.4.jar
  [✔️] chronos-carpet-extension-1.17.1-1.4.6.jar
  [✔️] cleancut-1.17-4.0-fabric.jar
  [✔️] cloth-api-2.1.62.jar
  [✔️] cloth-config-5.2.47-fabric.jar
  [✔️] cloth-config-5.3.63-fabric.jar
  [✔️] continuity-1.0.3+1.17.jar
  [✔️] cutefulmod-1.1.0.jar
  [✔️] deepslatecutting-1.2.2.jar
  [✔️] enhancedblockentities-0.5+1.17.jar
  [✔️] essentialaddons-1.17.1-1.0.6.jar
  [✔️] essentialaddons-1.17.1-1.1.4.jar
  [✔️] fabric-api-0.46.1+1.17.jar
  [✔️] fabric-carpet-1.17.1-1.4.57+v220119.jar
  [✔️] fabric-language-kotlin-1.7.1+kotlin.1.6.10.jar
  [✔️] ferritecore-3.1.0-fabric.jar
  [✔️] flytre-lib-1.4.3 (1).jar
  [✔️] grind-enchantments-1.3.0+1.17.1.jar
  [✔️] Harvest-fabric-1.16.1-1.0.1.jar
  [✔️] hydrogen-fabric-mc1.17.1-0.3.jar
  [✔️] indium-1.0.1+mc1.17.1.jar
  [✔️] inmis-2.3.2-1.17.1.jar
  [✔️] InventoryHUD-fabric-[1.17.x]-3.4.1.jar
  [✔️] InventorySorter-1.7.9-1.17.jar
  [✔️] iris-mc1.17.1-1.2.6.jar
  [✔️] itemscroller-fabric-1.17.1-craftfix-1.2.6.jar
  [✔️] krypton-0.1.4.jar
  [✔️] lazydfu-0.1.2.jar
  [✔️] litematica-fabric-1.17.1-0.9.0.jar
  [✔️] lithium-fabric-mc1.17.1-0.7.5.jar
  [✔️] magiclib-0.5.37.jar
  [✔️] malilib-fabric-1.17.1-0.10.0-dev.26.jar
  [✔️] MasaGadget-1.17.1-3.0.0.jar
  [✔️] minihud-fabric-1.17.1-0.20.0.jar
  [✔️] minitweaks-1.17.1-1.1.4+fix.jar
  [✔️] minitweaks-1.17.1-1.1.5.jar
  [✔️] mixintrace-1.1.1+1.17.jar
  [✔️] modmenu-2.0.14.jar
  [✔️] monsters-in-the-closet-1.0.2+1.17.jar
  [✔️] NaturesCompass-1.17.1-2.0.1-fabric.jar
  [✔️] NoFog-1.2.0_1.16.5-1.18.1-fabric.jar
  [✔️] notenoughcrashes-4.1.4+1.17.1-fabric (1).jar
  [✔️] OfflineSkins-1.17.1-v1-fabric.jar
  [✔️] PerfectAccuracy-1.1.jar
  [✔️] pistorder-mc1.17.1-v1.5.0-fabric.jar
  [✔️] plusls-carpet-addition-1.17.1-0.2.5.jar
  [✔️] recipecache-0.2.1-1.17.1.jar
  [✔️] replaymod-1.17.1-2.6.1 (1).jar
  [✔️] RoughlyEnoughItems-6.4.419.jar
  [✔️] servux-fabric-1.17.0-0.1.0.jar
  [✔️] shulker-dupe_1.17.x_1.0.0 (1).jar
  [✔️] Slotifier-1.17.1-1.0.1.jar
  [✔️] sodium-extra-mc1.17.1-0.3.9.jar
  [✔️] sodium-fabric-mc1.17.1-0.3.4+build.13.jar
  [✔️] spark-fabric.jar
  [✔️] subtick-1.17.1-1.4.0.jar
  [✔️] syncmatica-0.2.6.jar
  [✔️] syncmatica-1.16.5-0.3.2.jar
  [✔️] totos-carpet-tweaks-1.17.1-0.2.2.jar
  [✔️] tweakermore-mc1.17.1-v3.7.1.jar
  [✔️] tweakeroo-fabric-1.17.1-0.11.0.jar
  [✔️] tweakfork-fabric-1.17.1-1.2.3.jar
  [✔️] weirdaddons-1.17-1.4.0.jar
  [✔️] whereisit-1.17.1-1.14.3.jar
  [✔️] worldedit-mod-7.2.7.jar
  [✔️] worldspecificviewdistance-0.1.0-1.17.jar
  [✔️] Xaeros_Minimap_22.1.2_Fabric_1.17.1.jar
  [✔️] Xaeros_Minimap_22.13.0_Fabric_1.17.1.jar
  [✔️] XaerosWorldMap_1.20.1_Fabric_1.17.1.jar
  [✔️] XaerosWorldMap_1.26.2_Fabric_1.17.1.jar
  [✔️] xpbeacons-1.17-7.0.jar

Params:
  --username Lokemol --version 1.17.1 --gameDir Z:/Minecraft/MULTIMC/MultiMC/instances/1.17.1/.minecraft --assetsDir Z:/Minecraft/MULTIMC/MultiMC/assets --assetIndex 1.17 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx10112m, -Duser.language=en]

Minecraft process ID: 24240

Using onesix launcher.

[12:33:11] [main/INFO]: Loading Minecraft 1.17.1 with Fabric Loader 0.15.7
[12:33:11] [ForkJoinPool-1-worker-25/WARN]: The mod "harvest" contains invalid entries in its mod json:
- Unsupported root entry "links" at line 7 column 10
[12:33:11] [ForkJoinPool-1-worker-25/WARN]: Mod itemscroller uses the version craftfix-1.2.6 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'craftfix'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[12:33:11] [main/WARN]: Warnings were found!
 - Mod 'Sodium Extra' (sodium-extra) 0.3.9 recommends version 1.4.0 or later of reeses-sodium-options, which is missing!
	 - You should install version 1.4.0 or later of reeses-sodium-options for the optimal experience.
[12:33:11] [main/INFO]: Loading 155 mods:
	- architectury 2.10.12
	- autoconfig1u 3.3.1
	- bedrockminer 1.0.0
	- betterthanmending 1.3.0
	- carpet 1.4.57
	- carpet-extra 1.4.57
	- carpet-fixes 1.17.1-1.3.0+v211201
	- carpet-tis-addition 1.59.4
	   |-- conditional-mixin 0.6.2
	   \-- mixinextras 0.3.5
	- chronos-carpet-addons 1.4.6
	- cleancut 1.17-4.0-fabric
	- cloth-api 2.1.62
	   |-- cloth-client-events-v0 2.1.62
	   |-- cloth-common-events-v1 2.1.62
	   |-- cloth-datagen-api-v1 2.1.62
	   |-- cloth-scissors-api-v1 2.1.62
	   \-- cloth-utils-v1 2.1.62
	- cloth-config2 5.3.63
	   \-- cloth-basic-math 0.6.1
	- continuity 1.0.3+1.17
	- cutefulmod 1.1.0
	- deepslatecutting 1.2.2
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- maybe-more-data 1.0.0-1.17.1
	- enhancedblockentities 0.5+1.17
	   \-- advanced_runtime_resource_pack 0.4.3
	- essentialaddons 1.17.1-1.1.4
	- fabric 0.46.1+1.17
	   |-- fabric-api-base 0.4.0+cf39a74318
	   |-- fabric-api-lookup-api-v1 1.5.0+e821752d18
	   |-- fabric-biome-api-v1 3.2.2+cf39a74318
	   |-- fabric-blockrenderlayer-v1 1.1.6+cf39a74318
	   |-- fabric-command-api-v1 1.1.4+cf39a74318
	   |-- fabric-commands-v0 0.2.3+cf39a74318
	   |-- fabric-containers-v0 0.1.13+cf39a74318
	   |-- fabric-content-registries-v0 0.4.1+3447790d18
	   |-- fabric-crash-report-info-v1 0.1.6+cf39a74318
	   |-- fabric-dimensions-v1 2.0.15+b556f28c18
	   |-- fabric-entity-events-v1 1.4.1+377137cc18
	   |-- fabric-events-interaction-v0 0.4.12+e99fbe1218
	   |-- fabric-events-lifecycle-v0 0.2.4+cf39a74318
	   |-- fabric-game-rule-api-v1 1.0.8+cf39a74318
	   |-- fabric-item-api-v1 1.3.0+6617390918
	   |-- fabric-item-groups-v0 0.3.2+cf39a74318
	   |-- fabric-key-binding-api-v1 1.0.6+2a2bb57318
	   |-- fabric-keybindings-v0 0.2.4+cf39a74318
	   |-- fabric-lifecycle-events-v1 1.4.6+0392f3a618
	   |-- fabric-loot-tables-v1 1.0.5+cf39a74318
	   |-- fabric-mining-level-api-v1 1.0.3+cf39a74318
	   |-- fabric-mining-levels-v0 0.1.7+cf39a74318
	   |-- fabric-models-v0 0.3.1+cf39a74318
	   |-- fabric-networking-api-v1 1.0.14+cf39a74318
	   |-- fabric-networking-blockentity-v0 0.2.12+cf39a74318
	   |-- fabric-networking-v0 0.3.3+cf39a74318
	   |-- fabric-object-builder-api-v1 1.11.1+f907116918
	   |-- fabric-object-builders-v0 0.7.8+cf39a74318
	   |-- fabric-particles-v1 0.2.5+cf39a74318
	   |-- fabric-registry-sync-v0 0.8.0+ea29b33318
	   |-- fabric-renderer-api-v1 0.4.6+ce16ae5918
	   |-- fabric-renderer-indigo 0.4.10+ce16ae5918
	   |-- fabric-renderer-registries-v1 3.2.6+cf39a74318
	   |-- fabric-rendering-data-attachment-v1 0.1.6+cf39a74318
	   |-- fabric-rendering-fluids-v1 0.2.1+cf39a74318
	   |-- fabric-rendering-v0 1.1.7+cf39a74318
	   |-- fabric-rendering-v1 1.10.1+377137cc18
	   |-- fabric-resource-conditions-api-v1 1.0.1+591a0f2118
	   |-- fabric-resource-loader-v0 0.4.10+f09604ce18
	   |-- fabric-screen-api-v1 1.0.5+cf39a74318
	   |-- fabric-screen-handler-api-v1 1.1.9+cf39a74318
	   |-- fabric-structure-api-v1 1.2.0+48a9ad8918
	   |-- fabric-tag-extensions-v0 1.2.3+cf39a74318
	   |-- fabric-textures-v0 1.0.7+cf39a74318
	   |-- fabric-tool-attribute-api-v1 1.3.3+3b96517518
	   \-- fabric-transfer-api-v1 1.5.4+cf39a74318
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.6.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.6.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- ferritecore 3.1.0
	- flytre_lib 1.4.3
	   |-- flytre-lib-base 1.3.0
	   |-- flytre-lib-compat 1.0.0
	   |-- flytre-lib-config 1.1.0
	   |-- flytre-lib-event 1.0.1
	   |-- flytre-lib-gui 1.0.0
	   \-- flytre-lib-storage 2.3.2
	- grindenchantments 1.3.0+1.17.1
	- harvest 1.2.12
	- hydrogen 0.3
	- indium 1.0.1+mc1.17.1
	- inmis 2.3.2-1.17.1
	   \-- omega-config 1.0.4
	- inventoryhud 3.4.1
	- inventorysorter 1.7.9-1.17
	   \-- kyrptconfig 1.1.10-1.17
	        \-- blue_endless_jankson 1.2.1
	- iris 1.2.6
	   |-- fabric-api-base 0.4.0+cf39a74318
	   |-- fabric-key-binding-api-v1 1.0.6+2a2bb57318
	   |-- fabric-resource-loader-v0 0.4.10+f09604ce18
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_slf4j_slf4j-api 1.7.12
	- itemscroller craftfix-1.2.6
	- java 16
	- krypton 0.1.4
	   \-- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT
	- lazydfu 0.1.2
	- litematica 0.9.0
	- lithium 0.7.5
	- magiclib 0.5.37
	   \-- magiclib-1_17_1 0.5.37
	- malilib 0.10.0-dev.26
	- masa_gadget_mod-1_17_1 3.0.0
	- minecraft 1.17.1
	- minihud 0.20.0
	- minitweaks 1.1.5
	- mixintrace 1.1.1+1.17
	- modmenu 2.0.14
	- monsters_in_the_closet 1.0.2+1.17
	- naturescompass 1.17.1-2.0.1-fabric
	- no_fog 1.2.0+1.16.5-1.18.1
	- notenoughcrashes 4.1.4+1.17.1
	- offlineskins 1.17.1-v1-fabric
	- pca 0.2.5
	   \-- multiconnect-api 1.4.16
	- perfectaccuracy 1.1
	- pistorder 1.5.0
	- recipecache 0.2.1-1.17.1
	- replaymod 1.17.1-2.6.1
	- roughlyenoughitems 6.4.419
	- shulker-dupe 1.0.0
	- slotifier 1.17.1-1.0.1
	- sodium 0.3.4+build.13
	   \-- org_joml_joml 1.10.2
	- sodium-extra 0.3.9
	   |-- caffeineconfig 1.0.0
	   \-- fabric-lifecycle-events-v1 1.4.6+0392f3a618
	- spark 1.6.2
	   \-- fabric-permissions-api-v0 0.1-SNAPSHOT
	- subtick 1.17.1-1.4.0
	- syncmatica 1.16.5-0.3.2
	- totos-carpet-tweaks 1.17.1-0.2.2
	- tweakermore 3.7.1
	- tweakeroo 1.2.3
	- weirdaddons 1.17-1.4.0
	- whereisit 1.14.3
	- worldedit 7.2.7+9f3e795
	- worldspecificviewdistance 0.1.0-1.17
	- xaerominimap 22.13.0
	- xaeroworldmap 1.26.2
	- xpbeacons 7.0
[12:33:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Z:/Minecraft/MULTIMC/MultiMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[12:33:12] [main/INFO]: Compatibility level set to JAVA_16
[12:33:12] [main/WARN]: Reference map 'flytre-lib-compat-refmap.json' for flytre-lib-compat.mixins.json could not be read. If this is a development environment you can ignore this message
[12:33:12] [main/INFO]: Loaded configuration file for Lithium: 87 options available, 2 override(s) found
[12:33:12] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[12:33:12] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 1 override(s) found
[12:33:12] [main/INFO]: Loaded configuration file for Sodium Extra: 21 options available, 0 override(s) found
[12:33:13] [main/WARN]: Error loading class: grondag/canvas/terrain/region/input/InputRegion (java.lang.ClassNotFoundException: grondag/canvas/terrain/region/input/InputRegion)
[12:33:13] [main/WARN]: Mixin malte0811.ferritecore.mixin.mrl.ModelResourceLocationMixin is disabled as Hydrogen is installed
[12:33:13] [main/WARN]: Mixin malte0811.ferritecore.mixin.mrl.ResourceLocationAccess is disabled as Hydrogen is installed
[12:33:13] [main/WARN]: Mixin malte0811.ferritecore.mixin.dedupbakedquad.BakedQuadAccess is disabled as Hydrogen is installed
[12:33:13] [main/WARN]: Mixin malte0811.ferritecore.mixin.dedupbakedquad.SimpleModelBuilderMixin is disabled as Hydrogen is installed
[12:33:13] [main/WARN]: Mixin malte0811.ferritecore.mixin.chunknbt.ChunkSerializerMixin is disabled as Hydrogen is installed
[12:33:13] [main/WARN]: Force-disabling mixin 'world.inline_height.WorldChunkMixin' as rule 'mixin.world.inline_height' (added by user configuration) disables it and children
[12:33:13] [main/WARN]: Force-disabling mixin 'world.inline_height.WorldMixin' as rule 'mixin.world.inline_height' (added by user configuration) disables it and children
[12:33:13] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[12:33:13] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[12:33:13] [main/WARN]: Error loading class: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen (java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen)
[12:33:13] [main/WARN]: Error loading class: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen (java.lang.ClassNotFoundException: me/flashyreese/mods/reeses_sodium_options/client/gui/SodiumVideoOptionsScreen)
[12:33:13] [main/WARN]: [carpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinWorldChunkSetBlockHook
[12:33:13] [main/WARN]: Adding Mixin to disable Hydrogen's MixinState#postCreateWithTable
[12:33:13] [main/INFO]: I used the json to destroy the json
[12:33:13] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[12:33:13] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[12:33:13] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[12:33:13] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableMapEntry' (url: jar:file:/Z:/Minecraft/MULTIMC/MultiMC/instances/1.17.1/.minecraft/mods/hydrogen-fabric-mc1.17.1-0.3.jar!/com/google/common/collect/HydrogenImmutableMapEntry.class)
[12:33:13] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySetIterator' (url: jar:file:/Z:/Minecraft/MULTIMC/MultiMC/instances/1.17.1/.minecraft/mods/hydrogen-fabric-mc1.17.1-0.3.jar!/com/google/common/collect/HydrogenEntrySetIterator.class)
[12:33:13] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySet' (url: jar:file:/Z:/Minecraft/MULTIMC/MultiMC/instances/1.17.1/.minecraft/mods/hydrogen-fabric-mc1.17.1-0.3.jar!/com/google/common/collect/HydrogenEntrySet.class)
[12:33:13] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableReferenceHashMap' (url: jar:file:/Z:/Minecraft/MULTIMC/MultiMC/instances/1.17.1/.minecraft/mods/hydrogen-fabric-mc1.17.1-0.3.jar!/com/google/common/collect/HydrogenImmutableReferenceHashMap.class)
[12:33:13] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[12:33:13] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[12:33:14] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/fabricmc/mapping/reader/v2/TinyVisitor
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/mapping/reader/v2/TinyVisitor
	at net.minecraft.client.main.Main.handler$fcf000$notenoughcrashes$asSoonAsPossible(Main.java:1017) ~[minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java) ~[minecraft-1.17.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 10 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.mapping.reader.v2.TinyVisitor
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.client.main.Main.handler$fcf000$notenoughcrashes$asSoonAsPossible(Main.java:1017) ~[minecraft-1.17.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java) ~[minecraft-1.17.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 10 more
Process exited with exit code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 11 Jun 2024 11:33:26 -0600

**Comment by natanfudge** [comment]
Your Fabric Loader version is too new, use 1.14.x.
