### ISSUE TITLE
Entrypoint Catcher (loadcatcher) Causing Instant Crash

### ISSUE THREAD

**Issue by Ruskiiii** [natanfudge/Not-Enough-Crashes#24]
I wish I had more details on what is happening here, but this is the most bizarre Crash Encounter I've had.
Myself and a few other testers are unable to launch ANY versions of our mod pack that use this mod suddenly today, for whatever reason. 
Upon removal, everything seems to work just right.

When Downloading the modpack from CF it crashes.. but when using a previous untouched version it would have worked..
I'm letting you know in case you've changed anything or something withing CF has changed, so far I have not heard about this from anyone but its an extremely odd case..

**Comment by coderbot16** [comment]
This appears to be an issue with updating to Fabric Loader v0.10. Entrypoint Catcher's hacks into loader internals broke with the new update:

```
java.lang.NullPointerException
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement.preprocessMods(EntrypointCatcher.java:105)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement.run(EntrypointCatcher.java:83)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher.runEntrypointRedirection(EntrypointCatcher.java:53)
    at net.minecraft.class_310.redirect$zbm000$stopFabricInit(class_310.java:3800)
    at net.minecraft.class_310.<init>(class_310.java:423)
    at net.minecraft.client.main.Main.main(Main.java:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

A workaround is downgrading to Fabric Loader v0.9.

**Comment by Romz24** [comment]
I also encountered this error, it was not there before, it appeared after reinstalling minecraft.

```
java.lang.NullPointerException
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement.preprocessMods(EntrypointCatcher.java:105)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher$LoaderClientReplacement.run(EntrypointCatcher.java:83)
    at io.github.giantnuker.fabric.loadcatcher.EntrypointCatcher.runEntrypointRedirection(EntrypointCatcher.java:53)
    at net.minecraft.class_310.redirect$zbl000$stopFabricInit(class_310.java:3800)
    at net.minecraft.class_310.<init>(class_310.java:423)
    at net.minecraft.client.main.Main.main(Main.java:177)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
```

**Comment by natanfudge** [comment]
Issue not reproducible with Loader v0.11.1.
