### ISSUE TITLE
1.17 optifabric crash on game load

### ISSUE THREAD

**Issue by GeneShogo** [natanfudge/Not-Enough-Crashes#52]
[12:18:33] [main/INFO]: Loading for game Minecraft 1.17
[12:18:33] [ForkJoinPool-1-worker-23/WARN]: The mod "libcd" contains invalid entries in its mod json:

Unsupported root entry "licence" at line 9 column 12
[12:18:33] [ForkJoinPool-1-worker-9/WARN]: Non-Fabric mod JAR at "C:\Users\jondh\Twitch\Minecraft\Instances\Cave Update\mods\preview_OptiFine_1.17_HD_U_G9_pre20.jar", ignoring
[12:18:33] [main/WARN]: Warnings were found!
Conflicting versions found for fabric-api-base: used 0.3.0+a02b4463d5, also found 0.3.0+a02b44633d, 0.3.0+a02b4463a0
Conflicting versions found for fabric-api-lookup-api-v1: used 1.2.0+84310a227d, also found 1.2.0+2b5c62d03d
Conflicting versions found for fabric-resource-loader-v0: used 0.4.7+b7ab6121a0, also found 0.4.7+b7ab6121d5, 0.4.7+b7ab61213d
Mod 'Atmosfera' (atmosfera) conflicts with primalwinter:, which has an invalid mod ID because:
It contains invalid characters: ':'!
Conflicting versions found for fabric-screen-api-v1: used 1.0.4+198a96213d, also found 1.0.4+155f865c3d
Conflicting versions found for fabric-tag-extensions-v0: used 1.1.4+a02b4463d5, also found 1.1.4+a02b44633d
Mod 'BetterF3' (betterf3) recommends version 2.0.0.* of mod 'Mod Menu' (modmenu), but a non-matching version is present: 2.0.2!
You must install version 2.0.0.* of 'Mod Menu' (modmenu).
Mod 'Mod Menu' (modmenu) v2.0.2 is being loaded from the user's mod directory.
[12:18:33] [main/INFO]: [FabricLoader] Loading 171 mods:
advanced-xray-fabric@0.6.0-build.8
advanced_runtime_resource_pack@0.2.9
advancedcompass@1.2.1
advancements-enlarger@0.2.4
amecsapi@1.1.5+mc21w16a
animal_feeding_trough@1.0.2
appleskin@mc1.17-2.0.0
architectury@2.0.10
assembly@21w06a-1.0.0
atmosfera@1.4.0+mc1.17
auto_planter@17.1-fabric
autoconfig1u@3.3.1
backslot@1.1.12
backslotaddon@1.0.4
basicaiots@1.3.1
beaconoverhaul@1.4.0+1.17
betterf3@1.1.5
betterthirdperson@1.5.0
biomepicker@1.1
blue_endless_jankson@1.2.1
bright-ore@0.3.0
cardinal-components-base@3.0.0-nightly.1.17-pre2
cardinal-components-entity@3.0.0-nightly.1.17-pre2
carrier@1.8.0
cherishedworlds@1.4.1-1.17
cloth-basic-math@0.5.1
cloth-config2@5.0.34
comforts@0.0.4-1.17
controlling@1.1.2
croptopia@${mod_version}
croptosis@1.1.2
customportalapi@0.0.1-beta37-1.17
customstars@0.5
dawn@2.0.3
diggusmaximus@1.4.5-1.17
dragonloot@1.0.8
dual_riders@1.0.5
earthtojavamobs@1.7.1+1.17
emerald_tools@1.2.12
enchantingchanges@1.0.4
enhanced_attack_indicator@1.0.2+1.17
enhanced_mushrooms@1.0.4
expandedstorage@7.0.0-alpha.25
expcontainer@1.15.1
extragenerators@1.0.5-BETA+1.17
fabric@0.36.0+1.17
fabric-api-base@0.3.0+a02b4463d5
fabric-api-lookup-api-v1@1.2.0+84310a227d
fabric-biome-api-v1@3.1.11+c345aea83d
fabric-blockrenderlayer-v1@1.1.5+a02b44633d
fabric-command-api-v1@1.1.1+a02b44633d
fabric-commands-v0@0.2.2+92519afa3d
fabric-containers-v0@0.1.12+a02b44633d
fabric-content-registries-v0@0.2.2+a02b44633d
fabric-crash-report-info-v1@0.1.5+be9da3103d
fabric-dimensions-v1@2.0.10+a02b44633d
fabric-entity-events-v1@1.1.0+a02b44633d
fabric-events-interaction-v0@0.4.9+a722d8c03d
fabric-events-lifecycle-v0@0.2.1+92519afa3d
fabric-furnaces@2.0.1-1.17
fabric-game-rule-api-v1@1.0.6+a02b44633d
fabric-item-api-v1@1.2.4+a02b44633d
fabric-item-groups-v0@0.2.10+b7ab61213d
fabric-key-binding-api-v1@1.0.4+a02b44633d
fabric-keybindings-v0@0.2.2+36b77c3e3d
fabric-language-kotlin@1.6.1+kotlin.1.5.10
fabric-lifecycle-events-v1@1.4.4+a02b44633d
fabric-loot-tables-v1@1.0.4+a02b44633d
fabric-mining-levels-v0@0.1.3+92519afa3d
fabric-models-v0@0.3.0+a02b44633d
fabric-networking-api-v1@1.0.11+b7ab61213d
fabric-networking-blockentity-v0@0.2.11+a02b44633d
fabric-networking-v0@0.3.2+92519afa3d
fabric-object-builder-api-v1@1.10.9+b7ab61213d
fabric-object-builders-v0@0.7.3+a02b44633d
fabric-particles-v1@0.2.4+a02b44633d
fabric-registry-sync-v0@0.7.10+e2961fee3d
fabric-renderer-api-v1@0.4.3+676f40fa3d
fabric-renderer-indigo@0.4.8+a02b44633d
fabric-renderer-registries-v1@3.2.0+a02b44633d
fabric-rendering-data-attachment-v1@0.1.5+a02b44633d
fabric-rendering-fluids-v1@0.1.13+a02b44633d
fabric-rendering-v0@1.1.2+92519afa3d
fabric-rendering-v1@1.6.0+a02b44633d
fabric-resource-loader-v0@0.4.7+b7ab6121a0
fabric-screen-api-v1@1.0.4+198a96213d
fabric-screen-handler-api-v1@1.1.8+a02b44633d
fabric-structure-api-v1@1.1.11+e36969833d
fabric-tag-extensions-v0@1.1.4+a02b4463d5
fabric-textures-v0@1.0.6+a02b44633d
fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
fabricloader@0.11.6
fake-player-api@0.2.0
fallingleaves@1.7.0+1.17
fallingtree@2.11.5
fasttransferlib@0.4.2
fatxporbs@1.0.0
fiber@0.23.0-2
indrev@1.10.0-alpha.4
inmis@2.3.1-1.17
inventoryhud@3.3.2
jankson@3.0.1+j1.2.0
java@16
kyrptconfig@1.1.10-1.17
lazydfu@0.1.2
libblockattributes_core@0.9.0
libblockattributes_fluids@0.9.0
libblockattributes_items@0.9.0
libcd@3.0.3+1.16.3
libgui@4.0.0+1.17
libjf@1.0.2
libninepatch@1.1.0
litematica@0.0.0-dev.20210616.033538
luckyblocks@1.1
magna@0.3.0-1.17-pre4
malilib@0.10.0+dev.22
me_hypherionmc_simple-rpc-lib@2.0.1
minecraft@1.17
mining_dims@1.1.4
mm@2.2
modmenu@2.0.2
morerespawnanchors@1.0.1
morevillagers-fabric@2.0.1-SNAPSHOT
mostructures@1.2.0-1.17
netherite_items@1.1.0
newcaves@1.3
notenoughcrashes@3.3.1+1.17
npcvariety@2.0.0
omega-config@1.0.8
onsoulfire@1.17-1
optifabric@1.11.6
org_jetbrains_kotlin_kotlin-reflect@1.5.10
org_jetbrains_kotlin_kotlin-stdlib@1.5.10
org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.10
org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.10
org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.0
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.0
org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.1
org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.1
patchouli@1.17-52-FABRIC-SNAPSHOT
paxi@20w45a-1.0
promenade@2.1.2
quartzelv@1.2.2
reach-entity-attributes@2.1.1
rightclickharvest@1.2.3
roughlyenoughitems@6.0.254-alpha
sculkblocks@1.0.0
sentimentality3@1.2.5
shulkerutils@1.0.1-1.17
simple-rpc@1.17-2.2-fabric
simple_backpack@1.1.10
somnus@0.0.12-1.17
spawnermod@1.0.0
step-height-entity-attribute@1.0.0
team_reborn_energy@0.1.1
terraform-shapes-api-v1@1.0.4
tweed@3.0.0-beta.22
universal_ores@1.0
upgradedechests@1.0.1-1.17
upgradedshulkers@1.0.1-1.17
urns@1.0.0
vanillaplusbiomes@0.3.2
veinmining@0.0.9-1.17
versionchanger@1.2.2
villagernames@2.0.0
wandering_collector@1.0.2+mc1.17
waystones@2.0.1
witherite@0.0.5
woods_and_mires@1.1.0+1.17
wthit@3.5.3
xaerominimap@21.11.4
[12:18:33] [main/WARN]: Mod assembly (21w06a-1.0.0) does not respect SemVer - comparison support is limited.
[12:18:33] [main/WARN]: Mod paxi (20w45a-1.0) does not respect SemVer - comparison support is limited.
[12:18:33] [main/WARN]: Mod croptopia (${mod_version}) does not respect SemVer - comparison support is limited.
[12:18:33] [main/WARN]: Mod appleskin (mc1.17-2.0.0) does not respect SemVer - comparison support is limited.
[12:18:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/jondh/Twitch/Minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[12:18:37] [main/INFO]: Compatibility level set to JAVA_16
[12:18:40] [main/INFO]: Loading Mixin Config at org.featurehouse.mcmod.brightore.mixin.renderer
[12:18:40] [main/WARN]: Reference map 'EmeraldTools-Fabric-1.17-refmap.json' for emerald_tools.mixins.json could not be read. If this is a development environment you can ignore this message
[12:18:40] [main/WARN]: Reference map 'assembly-refmap.json' for assembly.mixins.json could not be read. If this is a development environment you can ignore this message
[12:18:40] [main/INFO]: Checking mod custom values
[12:18:40] [main/WARN]: @mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[12:18:46] [main/INFO]: Registering config for versionchanger
[12:18:46] [main/INFO]: I used the json to destroy the json
[12:18:46] [main/INFO]: Initializing StacktraceDeobfuscator
[12:18:47] [main/ERROR]: Failed to load mappings!
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:143) ~[?:?]
at fudge.notenoughcrashes.stacktrace.YarnVersion.getLatestBuildForCurrentVersion(YarnVersion.java:38) ~[notenoughcrashes-3.3.1+1.17-fabric.jar:?]
at fudge.notenoughcrashes.fabric.StacktraceDeobfuscator.downloadAndCacheMappings(StacktraceDeobfuscator.java:58) ~[notenoughcrashes-3.3.1+1.17-fabric.jar:?]
at fudge.notenoughcrashes.fabric.StacktraceDeobfuscator.init(StacktraceDeobfuscator.java:44) [notenoughcrashes-3.3.1+1.17-fabric.jar:?]
at net.minecraft.client.main.Main.handler$zkn000$asSoonAsPossible(Main.java:517) [intermediary-1.17.jar:?]
at net.minecraft.client.main.Main.main(Main.java) [intermediary-1.17.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
[12:18:47] [main/INFO]: Done initializing StacktraceDeobfuscator
[12:18:48] [main/WARN]: @ModifyVariable(@at("INVOKE")) Shift.BY=2 on magna.mixins.json:WorldRendererMixin::localvar$zzm000$appendBlockBreakingProgressions exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.

**Comment by natanfudge** [comment]
Does the game actually close?

**Comment by GeneShogo** [comment]
> Does the game actually close?

The game doesn't even load. Shows launcher, click play, then brought back to launcher with crash message. The above is the log of the crash.

**Comment by natanfudge** [comment]
Hey, please try to use [version 3.4.1](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes/files/3431586) and enable the `forceCrashScreen` config option. 
If the issue persists please post here the error log.

**Comment by natanfudge** [comment]
No response
