### ISSUE TITLE
Stacia Expert Modpack BloodMagic crash

### ISSUE THREAD

**Issue by Olorinmaiar** [natanfudge/Not-Enough-Crashes#78]
everytime i use the alchemy table or wear living armor it crashes. And now i cant join cause im constantly wearing the Living Armor.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/8/21 9:13 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at wayoftime.bloodmagic.common.item.ItemLivingArmor.hasElytraUpgrade(ItemLivingArmor.java:224) ~[?:1.16.4-3.1.4-24] {re:classloading}
	at wayoftime.bloodmagic.common.item.ItemLivingArmor.canElytraFly(ItemLivingArmor.java:210) ~[?:1.16.4-3.1.4-24] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeItemStack.canElytraFly(IForgeItemStack.java:489) ~[?:?] {re:computing_frames,re:mixin,re:classloading}
	at top.theillusivec4.caelus.api.CaelusApi.canElytraFly(CaelusApi.java:97) ~[?:property(class java.lang.String, provider(?))] {re:mixin,re:classloading}
	at top.theillusivec4.caelus.Caelus.playerTick(Caelus.java:67) ~[?:property(class java.lang.String, provider(?))] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_315_Caelus_playerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2408/508194762.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPlayerPreTick(BasicEventHooks.java:85) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:196) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:caelus.mixins.json:PlayerEntityMixin,pl:mixin:APP:ars_nouveau.mixins.json:ElytraPlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:PlayerMixin,pl:mixin:APP:assets/botania/botania.mixins.json:MixinPlayerEntity,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinIntegratedServer,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$34929/1154013578.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

**Comment by natanfudge** [comment]
Hey, this looks like a Blood Magic issue. 
Please [Open an issue for Blood Magic](https://github.com/WayofTime/BloodMagic/issues/new) and make sure to follow their guidelines. Specifically, include the **entire** crash log, not only what you think is relevant.
