### ISSUE TITLE
mouseClicked event handler

### ISSUE THREAD

**Issue by efffauw** [natanfudge/Not-Enough-Crashes#87]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 11/7/21, 1:16 AM
Description: mouseClicked event handler

java.util.ConcurrentModificationException
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at java.util.HashMap$Values.forEach(HashMap.java:1070)
	at net.minecraft.client.sound.SoundSystem.stopAll(SoundSystem:162)
	at net.minecraft.client.sound.SoundManager.stopAll(SoundManager:241)
	at net.minecraft.client.MinecraftClient.reset(MinecraftClient:2227)
	at net.minecraft.client.MinecraftClient.disconnect(MinecraftClient:2203)
	at net.minecraft.client.gui.screen.GameMenuScreen.method_19836(GameMenuScreen:77)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:40)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:121)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:490)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:101)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:165)
	at net.minecraft.client.util.Window.swapBuffers(Window:310)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1137)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:38)
	at net.minecraft.client.MinecraftClient.modify$cap000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:13108)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:750)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1070)
	at net.minecraft.class_1140.method_4843(class_1140.java:162)
	at net.minecraft.class_1144.method_4881(class_1144.java:241)
	at net.minecraft.class_310.method_18098(class_310.java:2227)
	at net.minecraft.class_310.method_18096(class_310.java:2203)
	at net.minecraft.class_433.method_19836(class_433.java:77)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:121)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_433
Stacktrace:
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at java.lang.Thread.getStackTrace(Thread.java:1596)
	at net.minecraft.util.crash.CrashReportSection.trimStackTraceEnd(CrashReportSection:520)
	at net.minecraft.util.crash.CrashReport.addElement(CrashReport:198)
	at net.minecraft.world.World.addDetailsToCrashReport(World:845)
	at net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld:370)
	at net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient:2399)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:747)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:38)
	at net.minecraft.client.MinecraftClient.modify$cap000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:13108)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:750)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Affected level --
Details:
	All players: 1 total; [class_746['Werlitra4446'/3615, l='ClientLevel', x=-2395.62, y=72.00, z=-273.38]]
	Chunk stats: 256, 98
	Level dimension: minecraft:overworld
	Level spawn location: World: (-157,63,188), Section: (at 3,15,12 in -10,3,11; chunk contains blocks -160,0,176 to -145,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 86965 game time, 57298 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:747)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:38)
	at net.minecraft.class_310.modify$cap000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:13108)
	at net.minecraft.class_310.method_1514(class_310.java:750)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1978257448 bytes (1886 MiB) / 3489660928 bytes (3328 MiB) up to 4194304000 bytes (4000 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.10
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: AMD Radeon(TM) Vega 8 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=27.20.11044.5003
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 12747.61
	Virtual memory used (MB): 11334.80
	Swap memory total (MB): 6656.00
	Swap memory used (MB): 0.00
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmn128M -Xmx4000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		amecsapi: Amecs API 1.1.5+mc21w16a
		antighost: AntiGhost 1.17.1-fabric0.36.1-1.1.4
		appleskin: AppleSkin mc1.17-2.1.3
		aqupdgrizzly: Grizzly Bear mob 1.17-1.2.0
		architectury: Architectury 2.6.35
		autoconfig1u: Auto Config v1 Updated 3.2.2
		backslot: BackSlot 1.2.2
		backslotaddon: BackSlot Addon 1.0.7
		betterbeds: Better Beds 1.2.0
		betterdungeons: YUNG's Better Dungeons 1.17-1.0.2
		betterthirdperson: Better Third Person 1.5.0
		caelus: Caelus API 0.0.16-1.17
		capes: Capes 1.2.2+1.17
		cardinal-components-base: Cardinal Components API (base) 3.0.0
		cardinal-components-entity: Cardinal Components API (entities) 3.0.0
		cardinal-components-item: Cardinal Components API (items) 3.0.0-nightly.1.17-pre2
		carrier: Carrier 1.8.1
		cavebiomes: Cave Biomes 0.6.3
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v5 5.0.38
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		coat: Coat 1.0.0-beta.12
		colormatic: Colormatic 2.3.0+mc.1.17.1
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		couplings: Couplings 1.5.0+1.17
		cozy_camping: Cozy Camping 1.0.0-1.17
		crawl: Crawl 0.9.3
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.3.2
		custom-fog: Custom Fog 2.0.0
		darkpaintings: Dark Paintings 4.0.2
		dawn: Dawn API 2.0.6
		doublejump: Double Jump Mod 1.0.1+mc1.17
		dsurround: §6Dynamic Surroundings§r: §eFabric Edition 0.0.4
		dynamicfps: Dynamic FPS 2.0.6
		eatinganimationid: Eating Animation 1.2
		elytratrinket: Elytra Trinket 2.0.1-1.17
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.41.3+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.1+ffbe6d8f18
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.12+ffbe6d8f18
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463d5
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.0+ef17126d18
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463d5
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afad5
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121d5
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.12+81e15a8918
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+81e15a8918
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121d5
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.1+ffbe6d8f18
		fabricloader: Fabric Loader 0.11.7
		fabrishot: Fabrishot 1.5.1
		fallingleaves: Falling Leaves 1.7.4+1.17.1
		fallingtree: FallingTree 2.14.3
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		harvest_scythes: Harvest Scythes 2.0.6
		hydrogen: Hydrogen 0.3
		illuminations: Illuminations 1.9
		indium: Indium 1.0.0+mc1.17.1
		inmis: Inmis 2.3.2-1.17.1
		inspecio: Inspecio 1.1.0+1.17
		itemmodelfix: Item Model Fix 1.0.2+1.17
		java: OpenJDK 64-Bit Server VM 16
		kirin: Kirin UI 1.9.1
		lambdabettergrass: LambdaBetterGrass 1.2.1+1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libzoomer: LibZoomer 0.2.1+1.17
		lithium: Lithium 0.7.4
		lovely_snails: Lovely Snails 1.0.3+1.17
		mavm: More Axolotl Variants Mod 1.0.5
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		mo_glass: Mo Glass 1.5-MC1.17.1
		modmenu: Mod Menu 2.0.14
		morebannerfeatures: More Banner Features 1.0.7
		morevillagers-fabric: MoreVillagersFabric 2.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.2.1-1.17
		notenoughanimations: NotEnoughAnimations 1.3.3
		notenoughcrashes: Not Enough Crashes 3.7.1+1.17.1
		npcvariety: NPC Variety 2.2.0
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		particlerain: Particle Rain 1.5.0
		pling: Pling 1.4.0
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		promenade: Promenade 2.1.2
		rare-ice: Rare Ice 0.3.0
		rocks: This Rocks! 1.5.1
		roughlyenoughitems: Roughly Enough Items 6.1.314-alpha
		scorch: Scorch 1.1.2
		shwfox: Shadew's Foxes 1.1+fabric
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.2
		smoothboot: Smooth Boot 1.16.5-1.6.0
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.3.2+build.7
		sodium-extra: Sodium Extra 0.3.5
		spruceui: SpruceUI 3.3.0+1.17
		strawdummy: Straw Dummy 1.5.0
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.4
		toolstats: Tool Stats 2.0.1
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		transliterationlib: TRansliterationLib 1.2.2
		trinketofundying: Trinket of Undying 2.0.0-1.17
		trinkets: Trinkets 3.0.4
		trinketshulkerboxes: Trinket Shulker Boxes 2.0.0-1.17
		tweed4_annotated: tweed4_annotated 1.2.0
		tweed4_base: tweed4_base 1.3.1
		tweed4_data: tweed4_data 1.2.0
		tweed4_data_hjson: tweed4_data_hjson 1.1.0
		tweed4_tailor_coat: tweed4_tailor_coat 1.0.1
		tweed4_tailor_screen: tweed4_tailor_screen 1.0.1
		vanillaplusbiomes: Vanilla Plus Biomes 0.3.2
		villagernames: Villager Names 2.0.0
		wandering_collector: Wandering Collector 1.0.3+mc1.17
		weaponthrow: Weapon Throw 1.17.1-1.4
		woods_and_mires: Woods and Mires 1.1.1+1.17
		yungsapi: YUNG's API 1.17-Fabric-19
	Launched Version: fabric-loader-0.11.7-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 3.2.13596 Core Profile Forward-Compatible Context 20.10.44.05 27.20.11044.5003, ATI Technologies Inc.
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Fabric Loader (fabricloader), Not Enough Crashes (notenoughcrashes)

**Comment by natanfudge** [comment]
I see no relation to NEC.
